//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ice1")]
        public string szServerName {
            get {
                return ((string)(this["szServerName"]));
            }
            set {
                this["szServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11006")]
        public string dwSwitchID {
            get {
                return ((string)(this["dwSwitchID"]));
            }
            set {
                this["dwSwitchID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6001")]
        public string Phone_ENG {
            get {
                return ((string)(this["Phone_ENG"]));
            }
            set {
                this["Phone_ENG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6002")]
        public string Phone_FRE {
            get {
                return ((string)(this["Phone_FRE"]));
            }
            set {
                this["Phone_FRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6013")]
        public string G2T_ENG {
            get {
                return ((string)(this["G2T_ENG"]));
            }
            set {
                this["G2T_ENG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6014")]
        public string G2T_FRE {
            get {
                return ((string)(this["G2T_FRE"]));
            }
            set {
                this["G2T_FRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6007")]
        public string Chat_ENG {
            get {
                return ((string)(this["Chat_ENG"]));
            }
            set {
                this["Chat_ENG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6008")]
        public string Chat_FRE {
            get {
                return ((string)(this["Chat_FRE"]));
            }
            set {
                this["Chat_FRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6020")]
        public string ChatApp_ENG {
            get {
                return ((string)(this["ChatApp_ENG"]));
            }
            set {
                this["ChatApp_ENG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6021")]
        public string ChatApp_FRE {
            get {
                return ((string)(this["ChatApp_FRE"]));
            }
            set {
                this["ChatApp_FRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6017")]
        public string Hlth_ENG {
            get {
                return ((string)(this["Hlth_ENG"]));
            }
            set {
                this["Hlth_ENG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6018")]
        public string Hlth_FRE {
            get {
                return ((string)(this["Hlth_FRE"]));
            }
            set {
                this["Hlth_FRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int cacheInterval {
            get {
                return ((int)(this["cacheInterval"]));
            }
            set {
                this["cacheInterval"] = value;
            }
        }
    }
}
