//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderBoard.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RAMEntities : DbContext
    {
        public RAMEntities()
            : base("name=RAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Proc_GetQueue_Result> Proc_GetQueue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetQueue_Result>("Proc_GetQueue");
        }
    
        public virtual ObjectResult<Proc_Last24Grade_Result> Proc_Last24Grade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Last24Grade_Result>("Proc_Last24Grade");
        }
    
        public virtual ObjectResult<Proc_LastHourGrade_Result> Proc_LastHourGrade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LastHourGrade_Result>("Proc_LastHourGrade");
        }
    
        public virtual ObjectResult<Proc_LastHourWaitTime_Result> Proc_LastHourWaitTime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LastHourWaitTime_Result>("Proc_LastHourWaitTime");
        }
    }
}
